import pandas as pd
import numpy as np
import json
import warnings
warnings.filterwarnings('ignore')

print("EDA Analysis Script - Generated by EDA Family")

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import seaborn as sns
    HAS_PLOT = True
    print("Plotting libraries available")
except ImportError:
    HAS_PLOT = False
    print("Plotting libraries not available")

print("Ready for analysis")